export const phones = [
  {
    id: 0,
    name: "9991",
    description: "laba  ola jaytwfs nahtswu",
    category: "Iphone",
    price: "1209zl",
    color: "",
    sale: true,
    saleAmount: 200,
  },
  {
    id: 1,
    name: "992229",
    description: "labaf gratrwa",
    category: "Iphone",
    price: "9zl",
    color: "",
    sale: true,
    saleAmount: 200,
  },
  {
    id: 2,
    name: "999mkla",
    description: "ahwyta cakuay wwabt",
    category: "samsung",
    price: "1209zl",
    color: "",
    sale: true,
    saleAmount: 200,
  },

  {
    id: 3,
    name: "999mkla",
    description: "ahwyta cakuay wwabt",
    category: "samsung",
    price: "1209zl",
    color: "",
    sale: true,
    saleAmount: 200,
  },
  {
    id: 4,
    name: "999mkla",
    description: "ahwyta cakuay wwabt",
    category: "samsung",
    price: "1209zl",
    color: "",
    sale: true,
    saleAmount: 200,
  },
  {
    id: 5,
    name: "999mkla",
    description: "ahwyta cakuay wwabt",
    category: "samsung",
    price: "1209zl",
    color: "",
    sale: true,
    saleAmount: 200,
  },
];
